### ISSUE TITLE
master does not compile

### ISSUE THREAD

**Issue by redstar** [gedaiu/vibe.dav#1]
Using dub with dependency `"vibe-dav": "~master"` does not compile.

Error message: `Missing package description for package at ../tested-atom/`.

Root cause is the unresolved local dependency `"tested-atom"`.

**Comment by redstar** [comment]
BTW: I suggest including `tested` only if unittests are enabled.

**Comment by gedaiu** [comment]
I think that would be the best approach.. but I use the `name` attribute and for that I will have to wrap all the tests in `version(unitest)`... or there is better solution?

**Comment by gedaiu** [comment]
I removed the tested dependency :)
